services:
  kafka:
    image: confluentinc/cp-kafka:7.8.3
    container_name: kafka
    ports:
      - "9092:9092"

    environment:
      KAFKA_KRAFT_MODE: 'true'

      CLUSTER_ID: '1L7g7nGhU-eAKfL--X266wo'
      KAFKA_NODE_ID: 1

      KAFKA_PROCESS_ROLES: broker,controller
      KAFKA_CONTROLLER_QUORUM_VOTERS: 1@kafka:9093
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1

      KAFKA_LISTENERS: INTERNAL://0.0.0.0:29092,EXTERNAL://0.0.0.0:9092,CONTROLLER://0.0.0.0:9093,LOCAL://0.0.0.0:9094
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: INTERNAL:SASL_SSL,EXTERNAL:SASL_SSL,CONTROLLER:PLAINTEXT,LOCAL:PLAINTEXT
      KAFKA_ADVERTISED_LISTENERS: INTERNAL://kafka:29092,EXTERNAL://localhost:9092,LOCAL://kafka:9094
      
      KAFKA_INTER_BROKER_LISTENER_NAME: INTERNAL
      KAFKA_CONTROLLER_LISTENER_NAMES: CONTROLLER

      KAFKA_SASL_ENABLED_MECHANISMS: SCRAM-SHA-256
      KAFKA_SASL_MECHANISM_INTER_BROKER_PROTOCOL: SCRAM-SHA-256
      KAFKA_OPTS: "-Djava.security.auth.login.config=/etc/kafka/secrets/kafka_jaas.conf"

      KAFKA_SSL_KEYSTORE_LOCATION: /etc/kafka/secrets/kafka.server.keystore.jks
      KAFKA_SSL_KEYSTORE_PASSWORD: ${KAFKA_SSL_KEYSTORE_PASSWORD}
      KAFKA_SSL_KEY_PASSWORD: ${KAFKA_SSL_KEY_PASSWORD}

      KAFKA_SSL_TRUSTSTORE_LOCATION: /etc/kafka/secrets/kafka.server.truststore.jks
      KAFKA_SSL_TRUSTSTORE_PASSWORD: ${KAFKA_SSL_TRUSTSTORE_PASSWORD}

      KAFKA_MESSAGE_MAX_BYTES: 10485760
      KAFKA_REPLICA_FETCH_MAX_BYTES: 10485760
      
      KAFKA_LOG_DIRS: /tmp/kraft-combined-logs

    volumes:
      - kafka_kraft:/var/lib/kafka/data
      - ./secrets:/etc/kafka/secrets
  kafka-init:
    image: confluentinc/cp-kafka:7.8.3
    container_name: kafka-init
    depends_on:
      - kafka
    environment:
      - KAFKA_USER=${KAFKA_USER}
      - KAFKA_PASSWORD=${KAFKA_PASSWORD}
    command: >
      bash -c "
        echo 'Waiting for Kafka to be ready...'
        cub kafka-ready -b kafka:9094 1 40

        echo 'Creating topic cv_uri_brute...'
        kafka-topics --create --if-not-exists --bootstrap-server kafka:9094 --partitions 1 --replication-factor 1 --topic cv_uri_brute

        echo 'Creating SCRAM user...'
        kafka-configs --bootstrap-server kafka:9094 --alter --add-config 'SCRAM-SHA-256=[password='$$KAFKA_PASSWORD']' --entity-type users --entity-name $$KAFKA_USER

        echo 'Kafka initialization complete!'
      "
  backend_service:
    build: ./backend
    container_name: backend_service
    ports:
      - "8000:8000"
    depends_on:
      - kafka
    environment:
      - KAFKA_BOOTSTRAP_SERVERS=kafka:29092
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
      - CONNECT_STRING=${CONNECT_STRING}
      - WALLET_PASSWORD=${WALLET_PASSWORD}
      - WALLET_LOCATION=/usr/src/app/wallet
      - KAFKA_USER=${KAFKA_USER}
      - KAFKA_PASSWORD=${KAFKA_PASSWORD}
      - SSL_CA_LOCATION=/usr/src/secrets/ca-cert.pem
      - EMAIL_SENDER=${EMAIL_SENDER}
      - EMAIL_PASSWORD=${EMAIL_PASSWORD}
      - SMTP_SERVER=${SMTP_SERVER}
      - SMTP_PORT=${SMTP_PORT}
    volumes:
    - ./db/Wallet_unidb:/usr/src/app/wallet
    - ./secrets:/usr/src/secrets
    - ./utils:/usr/src/app/app/utils
  frontend_service:
    build: ./frontend
    container_name: frontend_service
    ports:
      - "8501:8501"
    depends_on:
      - backend_service
    environment:
      - BACKEND_URL=http://backend_service:8000
  ollama:
    image: ollama/ollama:latest
    container_name: ollama
    ports:
      - "11434:11434"
    volumes:
      - ollama_data:/root/.ollama
  spark-master:
    build: 
      context: .
      dockerfile: Dockerfile.spark
    container_name: spark-master
    hostname: spark-master
    command: /opt/spark/bin/spark-class org.apache.spark.deploy.master.Master
    environment:
      - SPARK_MODE=master
      - SPARK_MASTER_HOST=spark-master
      - SPARK_MASTER_PORT=7077
      - SPARK_MASTER_WEBUI_PORT=8080
      - DB_USER=${DB_OWNER}
      - DB_PASS=${DB_OWNER_PASSWORD}
      - DB_DSN=unidb_tp
      - WALLET_LOCATION=/opt/spark/wallet
      - WALLET_PASSWORD=${WALLET_PASSWORD}
      - KAFKA_PASSWORD=${KAFKA_PASSWORD}
      - KAFKA_TRUSTSTORE_PASSWORD=${KAFKA_SSL_TRUSTSTORE_PASSWORD}
      - KAFKA_USER=${KAFKA_USER}
      - EMAIL_SENDER=${EMAIL_SENDER}
      - EMAIL_PASSWORD=${EMAIL_PASSWORD}
      - SMTP_SERVER=${SMTP_SERVER}
      - SMTP_PORT=${SMTP_PORT}
    ports:
      - '8080:8080'
      - '7077:7077'
    volumes:
      - ./spark-apps:/opt/spark-apps
      - ./spark-data:/opt/spark-data
      - ./secrets:/opt/spark/secrets
      - ./db/Wallet_unidb:/opt/spark/wallet
      - ./utils:/opt/utils

  spark-worker:
    build: 
      context: .
      dockerfile: Dockerfile.spark
    container_name: spark-worker
    hostname: spark-worker
    command: /opt/spark/bin/spark-class org.apache.spark.deploy.worker.Worker spark://spark-master:7077
    environment:
      - SPARK_WORKER_CORES=2
      - SPARK_WORKER_MEMORY=2g
      - SPARK_WORKER_WEBUI_PORT=8081
      - DB_USER=${DB_OWNER}
      - DB_PASS=${DB_OWNER_PASSWORD}
      - DB_DSN=unidb_tp
      - WALLET_LOCATION=/opt/spark/wallet
      - WALLET_PASSWORD=${WALLET_PASSWORD}
      - KAFKA_PASSWORD=${KAFKA_PASSWORD}
      - KAFKA_TRUSTSTORE_PASSWORD=${KAFKA_SSL_TRUSTSTORE_PASSWORD}
      - KAFKA_USER=${KAFKA_USER}
      - EMAIL_SENDER=${EMAIL_SENDER}
      - EMAIL_PASSWORD=${EMAIL_PASSWORD}
      - SMTP_SERVER=${SMTP_SERVER}
      - SMTP_PORT=${SMTP_PORT}
    ports:
      - '8081:8081'
    depends_on:
      - spark-master
    volumes:
      - ./spark-apps:/opt/spark-apps
      - ./spark-data:/opt/spark-data
      - ./secrets:/opt/spark/secrets
      - ./db/Wallet_unidb:/opt/spark/wallet
      - ./utils:/opt/utils
volumes:
  kafka_kraft:
  spark-apps:
  spark-data:
  ollama_data:
  utils: