
-- creare schema owner
CREATE USER recruit_owner IDENTIFIED BY "ComplexPass123!";
GRANT CREATE SESSION, CREATE TABLE, CREATE VIEW, CREATE PROCEDURE, CREATE TRIGGER TO recruit_owner;
GRANT UNLIMITED TABLESPACE TO recruit_owner;

-- creare service account

CREATE USER db_service_account IDENTIFIED BY "AppPass1234!";
GRANT CREATE SESSION TO db_service_account;

-- creare roluri 

CREATE ROLE role_recruiter_db;
CREATE ROLE role_hr_manager_db;

GRANT role_recruiter_db TO db_service_account;
GRANT role_hr_manager_db TO db_service_account;


-- creare schema
ALTER SESSION SET CURRENT_SCHEMA = recruit_owner;

CREATE TABLE KEY_STORE (
    key_id          NUMBER(10) GENERATED BY DEFAULT AS IDENTITY,
    key_name        VARCHAR2(50),
    encryption_key  RAW(32),
    created_at      DATE DEFAULT SYSDATE,
    CONSTRAINT pk_key_store PRIMARY KEY (key_id)
);

CREATE TABLE APP_USER (
    user_id         NUMBER(10) GENERATED BY DEFAULT AS IDENTITY,
    username        VARCHAR2(50) NOT NULL UNIQUE,
    password_hash   VARCHAR2(64),
    role            VARCHAR2(20) CHECK (role IN ('HR', 'RECRUITER', 'CANDIDATE')),
    is_active       NUMBER(1) DEFAULT 1,
    failed_attempts NUMBER DEFAULT 0,
    last_login      TIMESTAMP,
    is_locked       NUMBER(1) DEFAULT 0,
    created_at      TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT pk_app_user PRIMARY KEY (user_id)
);

CREATE TABLE INJECTION_ALERT (
    alert_id        NUMBER(10) GENERATED BY DEFAULT AS IDENTITY,
    ip_address      VARCHAR2(45),
    attack_pattern  VARCHAR2(255),
    query_attempt   CLOB,
    detected_at     TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT pk_injection_alert PRIMARY KEY (alert_id)
);

CREATE TABLE AUDIT_LOG (
    log_id          NUMBER(10) GENERATED BY DEFAULT AS IDENTITY,
    db_user         VARCHAR2(30),
    table_name      VARCHAR2(30),
    operation       VARCHAR2(10),
    old_value       VARCHAR2(4000),
    new_value       VARCHAR2(4000),
    log_timestamp   TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT pk_audit_log PRIMARY KEY (log_id)
);

CREATE TABLE CANDIDATE (
    candidate_id    NUMBER(10) GENERATED BY DEFAULT AS IDENTITY,
    user_id         NUMBER(10),
    first_name      VARCHAR2(50),
    last_name       VARCHAR2(50),
    email           VARCHAR2(100),
    phone           VARCHAR2(20),
    resume_file     BLOB,
    CONSTRAINT pk_candidate PRIMARY KEY (candidate_id),
    CONSTRAINT fk_candidate_user FOREIGN KEY (user_id) 
        REFERENCES APP_USER(user_id)
);

CREATE TABLE EDUCATION (
    edu_id          NUMBER(10) GENERATED BY DEFAULT AS IDENTITY,
    candidate_id    NUMBER(10),
    institution     VARCHAR2(100),
    degree          VARCHAR2(100),
    start_date      DATE,
    end_date        DATE,
    CONSTRAINT pk_education PRIMARY KEY (edu_id),
    CONSTRAINT fk_education_candidate FOREIGN KEY (candidate_id) 
        REFERENCES CANDIDATE(candidate_id)
);

CREATE TABLE CATEGORY (
    category_id     NUMBER(5) GENERATED BY DEFAULT AS IDENTITY,
    category_name   VARCHAR2(50),
    description     VARCHAR2(255),
    CONSTRAINT pk_category PRIMARY KEY (category_id)
);

CREATE TABLE JOB (
    job_id          NUMBER(10) GENERATED BY DEFAULT AS IDENTITY,
    category_id     NUMBER(5),
    title           VARCHAR2(100),
    description     CLOB,
    min_salary      NUMBER(10, 2),
    max_salary      NUMBER(10, 2),
    deadline        DATE,
    CONSTRAINT pk_job PRIMARY KEY (job_id),
    CONSTRAINT fk_job_category FOREIGN KEY (category_id) 
        REFERENCES CATEGORY(category_id)
);

CREATE TABLE JOB_APPLICATION (
    app_id          NUMBER(10) GENERATED BY DEFAULT AS IDENTITY,
    job_id          NUMBER(10),
    candidate_id    NUMBER(10),
    status          VARCHAR2(20) CHECK (status IN ('APPLIED', 'RECEIVED', 'PROCESSED_SECURE', 'INTERVIEW', 'OFFERED', 'REJECTED', 'WITHDRAWN', 'HIRED')),
    applied_at      DATE DEFAULT SYSDATE,
    CONSTRAINT pk_job_application PRIMARY KEY (app_id),
    CONSTRAINT fk_app_job FOREIGN KEY (job_id) 
        REFERENCES JOB(job_id),
    CONSTRAINT fk_app_candidate FOREIGN KEY (candidate_id) 
        REFERENCES CANDIDATE(candidate_id)
);

CREATE TABLE OFFER (
    offer_id        NUMBER(10) GENERATED BY DEFAULT AS IDENTITY,
    app_id          NUMBER(10),
    salary_encrypted RAW(2000),
    commission_pct  NUMBER(2,2),
    offer_date      DATE,
    CONSTRAINT pk_offer PRIMARY KEY (offer_id),
    CONSTRAINT fk_offer_app FOREIGN KEY (app_id) 
        REFERENCES JOB_APPLICATION(app_id)
);

CREATE TABLE SKILL (
    skill_id        NUMBER(5) GENERATED BY DEFAULT AS IDENTITY,
    skill_name      VARCHAR2(50),
    CONSTRAINT pk_skill PRIMARY KEY (skill_id)
);

CREATE TABLE JOB_SKILL (
    js_id           NUMBER(10) GENERATED BY DEFAULT AS IDENTITY,
    job_id          NUMBER(10),
    skill_id        NUMBER(5),
    CONSTRAINT pk_job_skill PRIMARY KEY (js_id),
    CONSTRAINT fk_js_job FOREIGN KEY (job_id) 
        REFERENCES JOB(job_id),
    CONSTRAINT fk_js_skill FOREIGN KEY (skill_id) 
        REFERENCES SKILL(skill_id)
);

-- create package
GRANT EXECUTE ON SYS.DBMS_CRYPTO TO recruit_owner;
GRANT EXECUTE ON SYS.DBMS_RLS TO recruit_owner;

CREATE OR REPLACE PACKAGE security_pkg IS
    FUNCTION get_key RETURN RAW;
    FUNCTION encrypt_salary(p_amount NUMBER) RETURN RAW;
    FUNCTION decrypt_salary(p_encrypted_data RAW) RETURN NUMBER;
    
    PROCEDURE app_login(p_user VARCHAR2, p_pass VARCHAR2, p_role OUT VARCHAR2);
    PROCEDURE set_session_context(p_user VARCHAR2, p_role VARCHAR2);
END security_pkg;
/

CREATE OR REPLACE PACKAGE BODY security_pkg IS

    FUNCTION get_key RETURN RAW IS 
        v_key RAW(32); v_count NUMBER; PRAGMA AUTONOMOUS_TRANSACTION;
    BEGIN
        SELECT count(*) INTO v_count FROM KEY_STORE WHERE key_name = 'SALARY_KEY';
        IF v_count = 0 THEN
            v_key := DBMS_CRYPTO.RANDOMBYTES(32);
            INSERT INTO KEY_STORE (key_name, encryption_key) VALUES ('SALARY_KEY', v_key);
            COMMIT;
        ELSE SELECT encryption_key INTO v_key FROM KEY_STORE WHERE key_name = 'SALARY_KEY'; END IF;
        RETURN v_key;
    END;

    FUNCTION encrypt_salary(p_amount NUMBER) RETURN RAW IS
        v_key RAW(32); v_src RAW(2000);
    BEGIN
        IF p_amount IS NULL THEN RETURN NULL; END IF;
        v_key := get_key();
        v_src := UTL_I18N.STRING_TO_RAW(TO_CHAR(p_amount), 'AL32UTF8');
        RETURN DBMS_CRYPTO.ENCRYPT(src=>v_src, typ=>DBMS_CRYPTO.ENCRYPT_AES256+DBMS_CRYPTO.CHAIN_CBC+DBMS_CRYPTO.PAD_PKCS5, key=>v_key);
    END;

    FUNCTION decrypt_salary(p_encrypted_data RAW) RETURN NUMBER IS
        v_key RAW(32); v_decrypted_raw RAW(2000);
    BEGIN
        IF p_encrypted_data IS NULL THEN RETURN 0; END IF;
        v_key := get_key();
        v_decrypted_raw := DBMS_CRYPTO.DECRYPT(src=>p_encrypted_data, typ=>DBMS_CRYPTO.ENCRYPT_AES256+DBMS_CRYPTO.CHAIN_CBC+DBMS_CRYPTO.PAD_PKCS5, key=>v_key);
        RETURN TO_NUMBER(UTL_I18N.RAW_TO_CHAR(v_decrypted_raw, 'AL32UTF8'));
    EXCEPTION WHEN OTHERS THEN RETURN -1;
    END;

    PROCEDURE app_login(p_user VARCHAR2, p_pass VARCHAR2, p_role OUT VARCHAR2) IS
        v_stored_hash VARCHAR2(64);
        v_role VARCHAR2(20);
        v_locked NUMBER;
    BEGIN

        SELECT password_hash, role, is_locked INTO v_stored_hash, v_role, v_locked
        FROM APP_USER WHERE username = p_user;
        
        IF v_locked = 1 THEN
            RAISE_APPLICATION_ERROR(-20001, 'Account Locked due to Security Policy.');
        END IF;

        IF v_stored_hash = p_pass THEN

            DBMS_SESSION.SET_CONTEXT('recruitment_ctx', 'ROLE', v_role);
            DBMS_SESSION.SET_CONTEXT('recruitment_ctx', 'USER', p_user);

            UPDATE APP_USER SET failed_attempts = 0, last_login = SYSTIMESTAMP WHERE username = p_user;
            COMMIT;
            
            p_role := v_role;
        ELSE

            UPDATE APP_USER SET failed_attempts = failed_attempts + 1 WHERE username = p_user;
            COMMIT;
            RAISE_APPLICATION_ERROR(-20002, 'Invalid Credentials');
        END IF;
    EXCEPTION
        WHEN NO_DATA_FOUND THEN
            RAISE_APPLICATION_ERROR(-20003, 'User not found');
    END;
    PROCEDURE set_session_context(p_user VARCHAR2, p_role VARCHAR2) IS
    BEGIN
        DBMS_SESSION.SET_CONTEXT('recruitment_ctx', 'ROLE', p_role);
        DBMS_SESSION.SET_CONTEXT('recruitment_ctx', 'USER', p_user);
    END set_session_context;
END security_pkg;
/

--  creare context
CREATE OR REPLACE CONTEXT recruitment_ctx USING security_pkg;

-- grant privilegii la roluri 

GRANT SELECT ON recruit_owner.JOB TO role_recruiter_db;
GRANT SELECT ON recruit_owner.JOB_APPLICATION TO role_recruiter_db;
GRANT SELECT ON recruit_owner.smart_candidate_view TO role_recruiter_db;

GRANT SELECT, INSERT, UPDATE ON recruit_owner.CANDIDATE TO role_hr_manager_db;
GRANT SELECT, INSERT, UPDATE ON recruit_owner.JOB_APPLICATION TO role_hr_manager_db;
GRANT SELECT, INSERT, UPDATE ON recruit_owner.OFFER TO role_hr_manager_db;
GRANT SELECT, INSERT, UPDATE ON recruit_owner.APP_USER TO role_hr_manager_db;
GRANT SELECT ON recruit_owner.AUDIT_LOG TO role_hr_manager_db;
GRANT EXECUTE ON recruit_owner.security_pkg TO role_hr_manager_db;

-- creare smart view

CREATE OR REPLACE VIEW smart_candidate_view AS
SELECT 
    c.candidate_id,
    c.first_name,
    c.last_name,
    c.email,
    CASE 
       
        WHEN SYS_CONTEXT('recruitment_ctx', 'ROLE') = 'HR' THEN c.phone
        
        ELSE '***-***-' || SUBSTR(c.phone, -4)
    END AS phone,
    ja.status,
    ja.app_id
FROM CANDIDATE c
JOIN JOB_APPLICATION ja ON c.candidate_id = ja.candidate_id;



-- creare triggere

CREATE OR REPLACE TRIGGER trg_audit_app_status
AFTER UPDATE OF status ON JOB_APPLICATION
FOR EACH ROW
BEGIN
    INSERT INTO AUDIT_LOG (db_user, table_name, operation, old_value, new_value)
    VALUES (
        SYS_CONTEXT('USERENV', 'SESSION_USER'), -- inregistreaza cine a facut modificarea 
        'JOB_APPLICATION',
        'UPDATE',
        :OLD.status,
        :NEW.status
    );
END;
/


CREATE OR REPLACE TRIGGER trg_audit_offer
AFTER INSERT OR UPDATE ON OFFER
FOR EACH ROW
DECLARE
    v_op VARCHAR2(10);
BEGIN
    IF INSERTING THEN v_op := 'INSERT'; ELSE v_op := 'UPDATE'; END IF;
    
    INSERT INTO AUDIT_LOG (db_user, table_name, operation, old_value, new_value)
    VALUES (
        SYS_CONTEXT('USERENV', 'SESSION_USER'),
        'OFFER',
        v_op,
        'N/A', 
        'Encrypted Salary Changed' 
    );
END;
/
COMMIT;

-- Inserts

INSERT INTO APP_USER (username, password_hash, role) 
VALUES ('hr_manager', '240be518fabd2724ddb6f04eeb1da5967448d7e831c08c8fa822809f74c720a9', 'HR');

INSERT INTO APP_USER (username, password_hash, role) 
VALUES ('recruiter_dan', '240be518fabd2724ddb6f04eeb1da5967448d7e831c08c8fa822809f74c720a9', 'RECRUITER');

INSERT INTO CATEGORY (category_name) VALUES ('IT');

INSERT INTO JOB (category_id, title, min_salary) VALUES (1, 'Python Dev', 5000);

INSERT INTO CANDIDATE (first_name, last_name, email) VALUES ('John', 'Doe', 'john@test.com');

INSERT INTO JOB_APPLICATION (job_id, candidate_id, status) VALUES (1, 1, 'APPLIED');

COMMIT;


DECLARE
    v_user_id NUMBER;
    v_cat_id NUMBER;
    v_job_id NUMBER;
    v_cand_id NUMBER;
BEGIN
    
    INSERT INTO CATEGORY (category_name, description) VALUES ('Human Resources', 'Recruitment and Employee Relations');
    INSERT INTO CATEGORY (category_name, description) VALUES ('Sales', 'B2B and B2C Sales');
    INSERT INTO CATEGORY (category_name, description) VALUES ('Finance', 'Accounting and Auditing');

    -- insert jobs
    FOR i IN 1..10 LOOP

        SELECT category_id INTO v_cat_id 
        FROM (SELECT category_id FROM CATEGORY ORDER BY DBMS_RANDOM.VALUE) 
        WHERE ROWNUM = 1;

        INSERT INTO JOB (category_id, title, description, min_salary, max_salary, deadline)
        VALUES (
            v_cat_id,
            'Job Position ' || i,
            'Description for position ' || i,
            4000 + (i * 100),
            8000 + (i * 200),
            SYSDATE + 30
        );
    END LOOP;

    -- insert app users & candidates 
    FOR i IN 1..10 LOOP
      
        INSERT INTO APP_USER (username, password_hash, role)
        VALUES (
            'candidate_gen_' || i, 
            '240be518fabd2724ddb6f04eeb1da5967448d7e831c08c8fa822809f74c720a9', -- hash pentru "admin123"
            'CANDIDATE'
        )
        RETURNING user_id INTO v_user_id; 

        INSERT INTO CANDIDATE (user_id, first_name, last_name, email, phone)
        VALUES (
            v_user_id,
            'Candidate' || i,
            'TestName' || i,
            'cand_gen_' || i || '@test.com',
            '070012300' || i
        );
    END LOOP;

    -- insert job app 
    FOR i IN 1..10 LOOP
        
        SELECT job_id INTO v_job_id FROM (SELECT job_id FROM JOB ORDER BY DBMS_RANDOM.VALUE) WHERE ROWNUM = 1;
       
        SELECT candidate_id INTO v_cand_id FROM (SELECT candidate_id FROM CANDIDATE ORDER BY DBMS_RANDOM.VALUE) WHERE ROWNUM = 1;
    
        BEGIN
            INSERT INTO JOB_APPLICATION (job_id, candidate_id, status, applied_at)
            VALUES (v_job_id, v_cand_id, 'APPLIED', SYSDATE - i);
        EXCEPTION 
            WHEN DUP_VAL_ON_INDEX THEN NULL;
        END;
    END LOOP;

    COMMIT;
END;
/

ALTER TABLE recruit_owner.JOB_APPLICATION ADD secure_resume_text CLOB;

ALTER TABLE recruit_owner.JOB_APPLICATION 
ADD CONSTRAINT ensure_json CHECK (secure_resume_text IS JSON);


CREATE OR REPLACE FUNCTION filter_secure_apps(p_schema IN VARCHAR2, p_object IN VARCHAR2)
RETURN VARCHAR2 IS
BEGIN
    IF SYS_CONTEXT('recruitment_ctx', 'ROLE') = 'RECRUITER' THEN
        RETURN 'status = ''PROCESSED_SECURE''';
    ELSE
        RETURN '1=1'; -- HR-ul vede tot
    END IF;
END;
/

BEGIN
  DBMS_RLS.ADD_POLICY(
    object_schema   => 'RECRUIT_OWNER',
    object_name     => 'JOB_APPLICATION',
    policy_name     => 'vpd_secure_apps_policy',
    function_schema => 'RECRUIT_OWNER',
    policy_function => 'filter_secure_apps',
    statement_types => 'SELECT'
  );
END;
/